"""empty message

Revision ID: d05a0426d2d0
Revises: 
Create Date: 2020-08-23 15:38:45.279136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd05a0426d2d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ptt_articles',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('board_name', sa.String(length=20), nullable=True),
    sa.Column('url', sa.String(length=80), nullable=True),
    sa.Column('article_date', sa.DateTime(), nullable=True),
    sa.Column('push_count', sa.Integer(), nullable=True),
    sa.Column('push_num', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=70), nullable=True),
    sa.Column('search_item', sa.String(length=20), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    op.drop_table('ptt_articles')
    # ### end Alembic commands ###
